version: '3'

services:
  backend:
    build:
      context: .  # Use the current directory as the build context
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=mydb
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    image: frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
